default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cloudify_development
  host: ec2-44-193-237-184.compute-1.amazonaws.com
  username: gjosrutzwrogrw
  password: 3451a10196e8a5858a455c772c5b2513cf2da5bf2f95a61818ed5335dd1e1b68
  port: 5432

test:
  <<: *default
  database: cloudify_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>